### PR TITLE
Translation code

### PR DESCRIPTION
**Pull request by GenshiX**
This is **_very_** simple code for implementing the translation feature, it involves a pre-trained model and seems to work pretty well. It has a method currently implemented which in theory should be able to be transposed over to the main program once its up and running, currently still working on ways to improve it. This should work (hopefully ) for the time being. it just needs to have input fed to it and it should both detect the language and translate it.

### CODE REVIEW

**Comment by zeshengchen** [comment]
If the pull request is ready for peer review, please invite all other group members to the list of "Reviewers".

**Review by zeshengchen — APPROVED** [review]
This is very simple change. I am going to approve it.

But what is the accuracy of the model used? Moreover, can it be used for any language to English or just certain languages?

**Review by demavior — APPROVED** [review]
I can see the translation working for the example usage. I can try to integrate this version for now.

**Review by rnavyaprabha — APPROVED** [review]
good to go.... try improving the accuracy

**Review by rboorugu14 — APPROVED** [review]
Hey, so I used DeepGram API for my code which is pretty good. Maybe try it to increase accuracy if it is low in your case too. (Just a suggestion)

**Comment by zeshengchen** [comment]
This pull request has been approved for a while. Why this pull request was not complete?

**Comment by zeshengchen** [comment]
@GenshiX As I talked to you in person, please make sure to contribute much more the implementation to this course project!

**Pull request merged**
