### PR TITLE
Base Code

### PR DESCRIPTION
**Pull request by rboorugu14**
Could someone run the code on their local system and test it? Based on this, I will build the project code. I have tried to run the code on the cloud, my local system, hugging face codespace, and google colab but could not get the transcription. I know the code is working but my device is having a microphone permission issue.

### CODE REVIEW

**Comment by demavior** [comment]
When I run on my system I get:
No speech detected in the current audio chunk.
Input overflow

When I run on google colab  I get:
An error occurred: Error querying device -1.

**Comment by rboorugu14** [comment]
Could you change the frame_buffer to 2048/4096?

**Review by rnavyaprabha — COMMENTED** [review]
I will try running the code on my local and get back to you

**Comment by rnavyaprabha** [comment]
I ran the code on local but it doesn't work as expected. Currently it translates into different words instead of actually words spoken can you please make changes in code such a way that it displays us the exact words spoken

**Review by demavior — APPROVED** [review]

**Review by rnavyaprabha — APPROVED** [review]
Please work on accuracy next sprint

**Review by GenshiX — APPROVED** [review]

**Pull request merged**
