### PR TITLE
Summarization

### PR DESCRIPTION
**Pull request by rnavyaprabha**
Review it and let me know if any changes needed

### CODE REVIEW

**Review by demavior — APPROVED** [review]
Everything appears to be working well. The OpenAI package needed to be installed with version 0.28. I’ll add this to requirements.txt.

**Review by rboorugu14 — APPROVED** [review]
Extra idea: We are only summarizing the speech-to-text notes here right? What if we also add an option to summarize pdf files?

**Comment by rnavyaprabha** [comment]
@rboorugu14 Good Idea let us add that to next sprint and develop it

**Comment by rnavyaprabha** [comment]
@GenshiX Thats right it is 0.28 version but if you view requirement.txt it is been added already so no need to add it again

**Review by GenshiX — APPROVED** [review]
Looks good to add this portion to main for now

**Pull request merged**
